services:
  # خدمة الويب (لموقع Flask)
  - type: web
    name: taskflow-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'taskflow_app:web_app'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: TELEGRAM_TOKEN
        value: 7358083777:AAF642Ecm_TdPDdUwXcchc8pTwRzTqAhDbM
      - key: EMAIL_FROM
        value: zoro7001@gmail.com
      - key: EMAIL_PASS
        value: ioaqzmfxmvxuety
      - key: SECRET_KEY
        generateValue: true # Render سيقوم بإنشاء مفتاح سري آمن تلقائيًا

  # العامل في الخلفية (لبوت التليجرام والمجدول)
  - type: worker
    name: taskflow-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python taskflow_app.py"
    # إضافة قرص صلب دائم لحفظ قاعدة البيانات
    disks:
      - name: data
        mountPath: /data
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: TELEGRAM_TOKEN
        value: 7358083777:AAF642Ecm_TdPDdUwXcchc8pTwRzTqAhDbM
      - key: EMAIL_FROM
        value: zoro7001@gmail.com
      - key: EMAIL_PASS
        value: ioaqzmfxmvxuety
      # نخبر الكود أن يستخدم القرص الصلب الدائم
      - key: RENDER_DISK_PATH
        value: /data
