services:
  - type: web
    name: taskflow-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn taskflow_app:web_app"
    envVars:
      - fromGroup: taskflow-secrets
    disk:
      name: taskflow-data
      mountPath: /data
      
  - type: worker
    name: taskflow-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python taskflow_app.py"
    envVars:
      - fromGroup: taskflow-secrets
    disk:
      name: taskflow-data
      mountPath: /data

disks:
  - name: taskflow-data
    sizeGB: 1
